'use client';

import React from 'react';
import type { LifePillarConfig } from '@/lib/pillarNarratives';
import type { KundliCalculations } from '@/types/kundali';
import { PLANET_NAMES, ZODIAC_SIGNS, SIGN_LORDS } from '@/lib/astrologyDictionary';

export interface ReportPlanet {
  name: string; sign: string; house: number; degree: string; nakshatra: string; retrograde: boolean; longitude: number;
}
export interface ReportHouse {
  house: number; sign: string; planets: string[];
}
export interface KundliReportProps {
  name: string;
  birthDetails: { birthDate: string; birthTime: string; latitude: number | null; longitude: number | null; timezone: string; };
  chartData: { lagna: string; ascendant: string; moonSign: string; sunSign: string; nakshatra: string; timezone: string; planets: ReportPlanet[]; houses: ReportHouse[]; };
  calculations?: KundliCalculations;
  pillars?: LifePillarConfig[];
  lang: 'en' | 'hi';
}

function locPlanet(lang: 'en' | 'hi', name: string): string { return PLANET_NAMES[lang]?.[name] ?? name; }
function locSign(lang: 'en' | 'hi', sign: string): string { return ZODIAC_SIGNS[lang]?.[sign] ?? sign; }
function signLord(sign: string): string {
  const names = ['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'];
  const idx = names.indexOf(sign);
  return idx >= 0 ? SIGN_LORDS[idx + 1] : '';
}
function tr(lang: 'en' | 'hi', en: string, hi: string): string { return lang === 'hi' ? hi : en; }
function yearOf(iso?: string): string { return iso ? new Date(iso).getFullYear().toString() : '—'; }

function SectionHeading({ title, subtitle }: { title: string; subtitle?: string }) {
  return (
    <div className="mb-6 pb-3 border-b-2 border-amber-400 dark:border-amber-500">
      <h2 className="text-xl font-bold font-serif text-indigo-950 dark:text-amber-300">{title}</h2>
      {subtitle && <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">{subtitle}</p>}
    </div>
  );
}
function DetailRow({ label, value }: { label: string; value: string }) {
  return (<><span className="text-slate-500 dark:text-slate-400">{label}:</span><span className="font-medium text-slate-800 dark:text-slate-200">{value || '—'}</span></>);
}
function Th({ children }: { children: React.ReactNode }) {
  return <th className="px-4 py-3 text-left text-xs font-bold uppercase tracking-wide text-slate-700 dark:text-slate-300 border-b-2 border-slate-300 dark:border-slate-600">{children}</th>;
}
function Td({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  return <td className={`px-4 py-3 ${className}`}>{children}</td>;
}

export default function KundliReport({ name, birthDetails, chartData, calculations, pillars, lang }: KundliReportProps) {
  const _t = (en: string, hi: string) => tr(lang, en, hi);
  const planets = chartData?.planets ?? [];
  const houses = chartData?.houses ?? [];
  const vimshottari = calculations?.vimshottari;
  const doshas = calculations?.doshas;
  const yogas = calculations?.yogas;
  const currentDasha = vimshottari?.currentDasha;
  const mahadashas = vimshottari?.mahadashas ?? [];
  const hasPillars = pillars && pillars.length > 0;

  return (
    <div className="report-root max-w-5xl mx-auto px-4 py-8 space-y-10">

      {/* COVER / BIRTH DETAILS */}
      <section className="print-page">
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold font-serif text-indigo-950 dark:text-amber-300 mb-2">
            {_t('Vedic Kundli Report', 'वैदिक कुंडली रिपोर्ट')}
          </h1>
          <p className="text-lg text-slate-600 dark:text-slate-300 font-medium">{name}</p>
          <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
            {_t('Generated by AstroSage AI', 'AstroSage AI द्वारा निर्मित')}
          </p>
        </div>
        <div className="astro-card max-w-2xl mx-auto">
          <h2 className="text-lg font-semibold font-serif text-indigo-950 dark:text-amber-300 mb-4 text-center">
            {_t('Birth Details', 'जन्म विवरण')}
          </h2>
          <div className="grid grid-cols-2 gap-4 text-sm">
            <DetailRow label={_t('Birth Date', 'जन्म तिथि')} value={birthDetails.birthDate} />
            <DetailRow label={_t('Birth Time', 'जन्म समय')} value={birthDetails.birthTime} />
            <DetailRow label={_t('Latitude', 'अक्षांश')} value={String(birthDetails.latitude ?? '—')} />
            <DetailRow label={_t('Longitude', 'देशांतर')} value={String(birthDetails.longitude ?? '—')} />
            <DetailRow label={_t('Timezone', 'समय क्षेत्र')} value={birthDetails.timezone} />
            <DetailRow label={_t('Ascendant (Lagna)', 'लग्न')} value={locSign(lang, chartData.lagna)} />
            <DetailRow label={_t('Moon Sign (Rashi)', 'चंद्र राशि')} value={locSign(lang, chartData.moonSign)} />
            <DetailRow label={_t('Sun Sign', 'सूर्य राशि')} value={locSign(lang, chartData.sunSign)} />
            <DetailRow label={_t('Nakshatra', 'नक्षत्र')} value={chartData.nakshatra} />
          </div>
        </div>
      </section>

      {/* PLANET POSITIONS TABLE */}
      <section className="print-page">
        <SectionHeading title={_t('Planetary Positions', 'ग्रह स्थिति')} />
        <div className="astro-card overflow-x-auto">
          <table className="w-full text-sm border-collapse">
            <thead>
              <tr className="bg-amber-50 dark:bg-amber-900/20">
                <Th>{_t('Planet', 'ग्रह')}</Th>
                <Th>{_t('Sign', 'राशि')}</Th>
                <Th>{_t('Sign Lord', 'राशि स्वामी')}</Th>
                <Th>{_t('Degree', 'अंश')}</Th>
                <Th>{_t('House', 'भाव')}</Th>
                <Th>{_t('Nakshatra', 'नक्षत्र')}</Th>
                <Th>{_t('State', 'अवस्था')}</Th>
              </tr>
            </thead>
            <tbody>
              {planets.map((p, i) => (
                <tr key={i} className="border-b border-slate-200 dark:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-800/50">
                  <Td className="font-semibold">{locPlanet(lang, p.name)}</Td>
                  <Td>{locSign(lang, p.sign)}</Td>
                  <Td>{locPlanet(lang, signLord(p.sign))}</Td>
                  <Td>{p.degree}</Td>
                  <Td>{p.house}</Td>
                  <Td>{p.nakshatra}</Td>
                  <Td>
                    {p.retrograde ? (
                      <span className="inline-block px-2 py-0.5 text-xs font-semibold rounded bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300">
                        {_t('Retro', 'वक्री')}
                      </span>
                    ) : (
                      <span className="inline-block px-2 py-0.5 text-xs font-semibold rounded bg-emerald-100 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-300">
                        {_t('Direct', 'सीधा')}
                      </span>
                    )}
                  </Td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
      {/* 12 HOUSES GRID */}
      <section className="print-page">
        <SectionHeading title={_t('Twelve Houses (Bhavas)', 'द्वादश भाव')} />
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {Array.from({ length: 12 }, (_, i) => i + 1).map((h) => {
            const houseData = houses.find((hh) => hh.house === h);
            const signName = houseData?.sign ?? '';
            const occupants = houseData?.planets ?? [];
            const lord = signLord(signName);
            return (
              <div key={h} className="astro-card p-4">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-sm font-bold text-indigo-900 dark:text-amber-300">
                    {_t(`House ${h}`, `भाव ${h}`)}
                  </span>
                  <span className="text-sm font-semibold text-violet-700 dark:text-violet-300">
                    {locSign(lang, signName)}
                  </span>
                </div>
                <div className="text-xs text-slate-600 dark:text-slate-400 space-y-1">
                  <div className="flex justify-between">
                    <span>{_t('Lord', 'स्वामी')}:</span>
                    <span className="font-medium">{locPlanet(lang, lord) || '—'}</span>
                  </div>
                  <div className="flex justify-between">
                    <span>{_t('Occupants', 'निवासी')}:</span>
                    <span className="font-medium">
                      {occupants.length > 0 ? occupants.map((p) => locPlanet(lang, p)).join(', ') : '—'}
                    </span>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </section>
      {/* SIX LIFE PILLARS — Full narratives + milestones */}
      {hasPillars && (
        <section className="print-page">
          <SectionHeading title={_t('Six Life Pillars', 'छह जीवन स्तंभ')} />
          <div className="space-y-8">
            {pillars!.map((pillar) => {
              const pTitle = lang === 'hi' ? pillar.titleHi : pillar.titleEn;
              const pNarr = lang === 'hi' ? pillar.narrativeHi : pillar.narrativeEn;
              const b = pillar.badges;
              return (
                <div key={pillar.key} className="astro-card p-6">
                  <div className="flex flex-wrap items-center gap-3 mb-4">
                    <h3 className="text-lg font-bold font-serif text-indigo-950 dark:text-amber-300">{pTitle}</h3>
                    {b && (
                      <div className="flex flex-wrap gap-2 ml-auto">
                        {b.score && (<span className="inline-block px-3 py-1 text-xs font-semibold rounded-full bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300">{_t('Score', 'स्कोर')}: {b.score}</span>)}
                        {b.timeframe && (<span className="inline-block px-3 py-1 text-xs font-semibold rounded-full bg-violet-100 text-violet-800 dark:bg-violet-900/30 dark:text-violet-300">{b.timeframe}</span>)}
                        {b.lord && (<span className="inline-block px-3 py-1 text-xs font-semibold rounded-full bg-cyan-100 text-cyan-800 dark:bg-cyan-900/30 dark:text-cyan-300">{_t('Lord', 'स्वामी')}: {locPlanet(lang, b.lord)}</span>)}
                      </div>
                    )}
                  </div>
                  <div className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed mb-4 pl-4 border-l-4 border-amber-400 dark:border-amber-500">
                    <p className="whitespace-pre-line">{pNarr}</p>
                  </div>
                  {pillar.milestones && pillar.milestones.length > 0 && (
                    <table className="w-full text-xs border-collapse">
                      <thead><tr className="bg-slate-100 dark:bg-slate-800"><Th>{_t('Period', 'अवधि')}</Th><Th>{_t('Event', 'घटना')}</Th><Th>{_t('Note', 'टिप्पणी')}</Th><Th>{_t('Outcome', 'परिणाम')}</Th></tr></thead>
                      <tbody>{pillar.milestones.map((m, mi) => (
                        <tr key={mi} className="border-b border-slate-200 dark:border-slate-700">
                          <Td className="font-medium whitespace-nowrap">{m.period}</Td><Td>{m.event}</Td><Td className="text-slate-600 dark:text-slate-400">{m.note || '—'}</Td>
                          <Td>{m.outcome === 'positive' ? (<span className="px-2 py-0.5 text-xs font-semibold rounded bg-emerald-100 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-300">{_t('Positive', 'शुभ')}</span>) : m.outcome === 'caution' ? (<span className="px-2 py-0.5 text-xs font-semibold rounded bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-300">{_t('Caution', 'सावधानी')}</span>) : m.outcome === 'neutral' ? (<span className="px-2 py-0.5 text-xs font-semibold rounded bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300">{_t('Neutral', 'तटस्थ')}</span>) : '—'}</Td>
                        </tr>
                      ))}</tbody>
                    </table>
                  )}
                </div>
              );
            })}
          </div>
        </section>
      )}
      {/* DOSHAS with remedies */}
      {doshas && (
        <section className="print-page">
          <SectionHeading title={_t('Dosha Analysis', 'दोष विश्लेषण')} />
          <div className="space-y-6">
            <DoshaCard lang={lang} title={_t('Mangal Dosha (Mars)', 'मंगल दोष')} present={doshas.mangal?.isPresent ?? false} severity={doshas.mangal?.severity} isNeutralized={doshas.mangal?.isNeutralized} description={doshas.mangal?.description} remedies={doshas.mangal?.remedies ?? []} />
            <DoshaCard lang={lang} title={_t('Sade Sati (Saturn)', 'साढ़े साती')} present={doshas.sadeSati?.isActive ?? false} severity={doshas.sadeSati?.isActive ? 'moderate' : 'none'} description={doshas.sadeSati?.description} remedies={doshas.sadeSati?.remedies ?? []} />
            <DoshaCard lang={lang} title={_t('Kaal Sarp Dosha', 'काल सर्प दोष')} present={doshas.kaalSarp?.isPresent ?? false} severity={doshas.kaalSarp?.isPresent ? 'moderate' : 'none'} description={doshas.kaalSarp?.description} remedies={doshas.kaalSarp?.remedies ?? []} />
          </div>
        </section>
      )}

      {/* YOGAS with strengths */}
      {yogas && (
        <section className="print-page">
          <SectionHeading title={_t('Yoga Analysis', 'योग विश्लेषण')} />
          <div className="astro-card overflow-x-auto">
            <table className="w-full text-sm border-collapse">
              <thead><tr className="bg-violet-50 dark:bg-violet-900/20"><Th>{_t('Yoga', 'योग')}</Th><Th>{_t('Strength', 'शक्ति')}</Th><Th>{_t('Description', 'विवरण')}</Th></tr></thead>
              <tbody>
                {yogas.gajakesari?.isPresent && <YogaRow lang={lang} name={yogas.gajakesari.name} strength={yogas.gajakesari.strength} description={yogas.gajakesari.description} />}
                {yogas.budhaditya?.isPresent && <YogaRow lang={lang} name={yogas.budhaditya.name} strength={yogas.budhaditya.strength} description={yogas.budhaditya.description} />}
                {(yogas.dhanaYogas ?? []).filter((dy) => dy.isPresent).map((dy, i) => (<YogaRow key={`d${i}`} lang={lang} name={dy.name} description={dy.description} />))}
                {!yogas.gajakesari?.isPresent && !yogas.budhaditya?.isPresent && (yogas.dhanaYogas ?? []).filter((dy) => dy.isPresent).length === 0 && (
                  <tr><td colSpan={3} className="text-center text-slate-500 dark:text-slate-400 py-6 italic">{_t('No major yoga combinations were detected.', 'कोई प्रमुख योग संयुक्त नहीं पाया गया।')}</td></tr>
                )}
              </tbody>
            </table>
          </div>
        </section>
      )}
      {/* VIMSHOTTARI DASHA with antardasha tables */}
      {mahadashas.length > 0 && (
        <section className="print-page">
          <SectionHeading title={_t('Vimshottari Dasha (120-Year Cycle)', 'विम्शोत्तरी दशा (120 वर्ष चक्र)')} />
          {currentDasha && (
            <div className="flex flex-wrap gap-3 mb-6">
              <span className="inline-block px-4 py-2 text-sm font-semibold rounded-full bg-rose-100 text-rose-800 dark:bg-rose-900/30 dark:text-rose-300">{_t('Running Mahadasha', 'चल रही महादशा')}: {locPlanet(lang, currentDasha.mahadasha)}</span>
              <span className="inline-block px-4 py-2 text-sm font-semibold rounded-full bg-violet-100 text-violet-800 dark:bg-violet-900/30 dark:text-violet-300">{_t('Antardasha', 'अंतर्दशा')}: {locPlanet(lang, currentDasha.antardasha)}</span>
              <span className="inline-block px-4 py-2 text-sm font-semibold rounded-full bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300">{yearOf(currentDasha.startDate)} – {yearOf(currentDasha.endDate)}</span>
            </div>
          )}
          <div className="astro-card overflow-x-auto mb-8">
            <table className="w-full text-sm border-collapse">
              <thead><tr className="bg-amber-50 dark:bg-amber-900/20"><Th>{_t('Mahadasha', 'महादशा')}</Th><Th>{_t('Start', 'प्रारंभ')}</Th><Th>{_t('End', 'समाप्ति')}</Th><Th>{_t('Years', 'वर्ष')}</Th></tr></thead>
              <tbody>{mahadashas.map((md, i) => { const isC = currentDasha && md.lord === currentDasha.mahadasha; return (<tr key={i} className={`border-b border-slate-200 dark:border-slate-700 ${isC ? 'bg-amber-50 dark:bg-amber-900/10 font-semibold' : ''}`}><Td>{locPlanet(lang, md.lord)}</Td><Td>{yearOf(md.startDate)}</Td><Td>{yearOf(md.endDate)}</Td><Td>{md.years}</Td></tr>); })}</tbody>
            </table>
          </div>
          <h3 className="text-lg font-semibold font-serif text-indigo-950 dark:text-amber-300 mb-4">{_t('Antardasha Breakdown', 'अंतर्दशा विवरण')}</h3>
          <div className="space-y-6">
            {mahadashas.map((md, mi) => {
              const ads = md.antardashas ?? [];
              if (ads.length === 0) return null;
              return (
                <div key={mi} className="astro-card overflow-x-auto">
                  <h4 className="text-sm font-bold text-indigo-900 dark:text-amber-200 mb-3">{locPlanet(lang, md.lord)} {_t('Mahadasha', 'महादशा')} ({yearOf(md.startDate)}–{yearOf(md.endDate)})</h4>
                  <table className="w-full text-xs border-collapse">
                    <thead><tr className="bg-slate-100 dark:bg-slate-800"><Th>#</Th><Th>{_t('Antardasha', 'अंतर्दशा')}</Th><Th>{_t('Start', 'प्रारंभ')}</Th><Th>{_t('End', 'समाप्ति')}</Th></tr></thead>
                    <tbody>{ads.map((ad, ai) => { const isCur = ad.planet === currentDasha?.antardasha && md.lord === currentDasha?.mahadasha; return (<tr key={ai} className={`border-b border-slate-200 dark:border-slate-700 ${isCur ? 'bg-amber-50 dark:bg-amber-900/10 font-semibold' : ''}`}><Td>{ai + 1}</Td><Td>{locPlanet(lang, ad.planet)}</Td><Td>{yearOf(ad.startDate)}</Td><Td>{yearOf(ad.endDate)}</Td></tr>); })}</tbody>
                  </table>
                </div>
              );
            })}
          </div>
        </section>
      )}

      {/* FOOTER DISCLAIMER */}
      <section className="border-t border-slate-200 dark:border-slate-700 pt-6 text-center">
        <p className="text-xs text-slate-500 dark:text-slate-400">
          {_t('This report is generated for guidance and educational purposes only. It is not a substitute for professional medical, legal, or financial advice.', 'यह रिपोर्ट केवल मार्गदर्शन और शैक्षिक उद्देश्य के लिए तैयार की गई है। यह पेशेवर चिकित्सा, कानूनी या वित्तीय सलाह का स्थान नहीं लेती।')}
        </p>
        <p className="text-xs text-slate-400 dark:text-slate-500 mt-2">AstroSage AI © {new Date().getFullYear()}</p>
      </section>
    </div>
  );
}
// ─── Sub-components ───────────────────────────────────────────────────────────

function YogaRow({ lang, name, strength, description }: { lang: 'en' | 'hi'; name: string; strength?: string; description: string }) {
  const sLabel = !strength ? '\u2014' : strength === 'strong' ? tr(lang, 'Strong', 'शक्तिशाली') : strength === 'moderate' ? tr(lang, 'Moderate', 'मध्यम') : tr(lang, 'Weak', 'कमज़ोर');
  return (
    <tr className="border-b border-slate-200 dark:border-slate-700">
      <Td className="font-semibold">{name}</Td>
      <Td><span className={`inline-block px-2 py-0.5 text-xs font-semibold rounded ${strength === 'strong' ? 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-300' : strength === 'moderate' ? 'bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300' : 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-400'}`}>{sLabel}</span></Td>
      <Td className="text-slate-600 dark:text-slate-400">{description || '\u2014'}</Td>
    </tr>
  );
}

function DoshaCard({ lang, title, present, severity, isNeutralized, description, remedies }: {
  lang: 'en' | 'hi'; title: string; present: boolean; severity?: string; isNeutralized?: boolean; description?: string; remedies: string[];
}) {
  const sevLabel = !severity || severity === 'none' ? tr(lang, 'None', 'कोई नहीं') : severity === 'mild' ? tr(lang, 'Mild', 'हल्का') : severity === 'moderate' ? tr(lang, 'Moderate', 'मध्यम') : tr(lang, 'Severe', 'गंभीर');
  return (
    <div className="astro-card p-6">
      <div className="flex flex-wrap items-center gap-3 mb-3">
        <h3 className="text-lg font-bold text-indigo-950 dark:text-amber-300">{title}</h3>
        <span className={`inline-block px-3 py-1 text-xs font-semibold rounded-full ${present ? 'bg-rose-100 text-rose-800 dark:bg-rose-900/30 dark:text-rose-300' : 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-300'}`}>
          {present ? tr(lang, 'Present', 'उपस्थित') : tr(lang, 'Absent', 'अनुपस्थित')}
        </span>
        {present && (<span className="inline-block px-3 py-1 text-xs font-semibold rounded-full bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300">{tr(lang, 'Severity', 'गंभीरता')}: {sevLabel}</span>)}
        {present && isNeutralized !== undefined && (
          <span className={`inline-block px-3 py-1 text-xs font-semibold rounded-full ${isNeutralized ? 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-300' : 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-400'}`}>
            {isNeutralized ? tr(lang, 'Neutralized', 'निर्प्रभावी') : tr(lang, 'Active', 'सक्रिय')}
          </span>
        )}
      </div>
      {description && (<p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed mb-4 pl-4 border-l-4 border-rose-300 dark:border-rose-500">{description}</p>)}
      {remedies.length > 0 && (
        <>
          <h4 className="text-sm font-semibold text-indigo-900 dark:text-amber-200 mb-2">{tr(lang, 'Remedies', 'उपाय')}</h4>
          <ul className="space-y-1.5">{remedies.map((r, i) => (<li key={i} className="text-sm text-slate-600 dark:text-slate-400 flex items-start gap-2"><span className="text-amber-500 mt-0.5">•</span><span>{r}</span></li>))}</ul>
        </>
      )}
    </div>
  );
}
