// lib/KundliPdfTemplate.ts - Simplified HTML template for Kundli PDF.
// Uses only basic CSS that html-pdf-lite can handle.

export interface PlanetPosition {
  name: string;
  sign: string;
  degree: string;
  house: number;
  retrograde: boolean;
  nakshatra?: string;
}

export interface HouseCusp {
  house: number;
  sign: string;
}

export interface ChartSlice {
  lagna: string;
  ascendant: string;
  moonSign: string;
  sunSign: string;
  nakshatra: string;
  planets: PlanetPosition[];
  houses: HouseCusp[];
}

export interface DoshaItem {
  name: string;
  isPresent: boolean;
  severity?: "low" | "moderate" | "high";
  description: string;
  remedies: string[];
}

export interface YogaItem {
  name: string;
  isPresent: boolean;
  strength?: "weak" | "moderate" | "strong";
  description: string;
  impact?: string;
  planets?: string[];
}

export interface Antardasha {
  planet: string;
  startDate: string;
  endDate: string;
}

export interface Mahadasha {
  lord: string;
  startDate: string;
  endDate: string;
  years: number;
  antardashas: Antardasha[];
}

export interface VimshottariReport {
  mahadashas: Mahadasha[];
  currentDasha: {
    mahadasha: string;
    antardasha: string;
    startDate: string;
    endDate: string;
  };
  birthMahadasha: string;
}

export interface PillarMilestone {
  period: string;
  event: string;
  note?: string;
  outcome?: "positive" | "neutral" | "caution";
}

export interface LifePillar {
  key: string;
  titleEn: string;
  titleHi?: string;
  badges?: { score?: string; timeframe?: string; lord?: string };
  narrativeEn: string;
  narrativeHi?: string;
  milestones: PillarMilestone[];
}

export interface KundliPdfData {
  name: string;
  birthDate: string;
  birthTime: string;
  latitude: number;
  longitude: number;
  timezone: string;
  chartData: ChartSlice;
  calculations: {
    vimshottari?: VimshottariReport;
    doshas?: DoshaItem[];
    yogas?: YogaItem[];
  };
  pillars: LifePillar[];
  language?: "en" | "hi";
}

function esc(s: unknown): string {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function txt(s: unknown): string {
  const v = String(s ?? "").trim();
  return v ? esc(v) : "\u2014";
}

export function generateKundliHtml(data: KundliPdfData, lang: "en" | "hi" = "en"): string {
  const d = data;
  const isHi = lang === "hi";
  const chart = d.chartData;
  const calc = d.calculations;

  const CSS = `<style>
    body { font-family: Arial, sans-serif; font-size: 10pt; color: #1a1a2e; margin: 0; padding: 10px; }
    .page-break { page-break-after: always; }
    h1 { font-size: 18pt; color: #2c3e50; margin: 0 0 10px 0; }
    h2 { font-size: 14pt; color: #2c3e50; margin: 0 0 8px 0; }
    p { margin: 0 0 8px 0; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 10px; font-size: 9pt; }
    th, td { border: 1px solid #999; padding: 4px 6px; text-align: left; }
    th { background-color: #eee; }
    .center { text-align: center; }
    .label { font-weight: bold; }
  </style>`;

  let html = `<!DOCTYPE html>
<html><head><meta charset="UTF-8">${CSS}</head><body>
`;

  // Cover
  html += `<div class="page-break center">
  <h1>${isHi ? "वैदिक कुंडली रिपोर्ट" : "Vedic Kundli Report"}</h1>
  <p>${isHi ? "AstroSage AI द्वारा निर्मित" : "Generated by AstroSage AI"}</p>
  <p><b>${txt(d.name)}</b></p>
  <table>
    <tr><td class="label">${isHi ? "जन्म तिथि" : "Birth Date"}</td><td>${txt(d.birthDate)}</td></tr>
    <tr><td class="label">${isHi ? "जन्म समय" : "Birth Time"}</td><td>${txt(d.birthTime)}</td></tr>
    <tr><td class="label">${isHi ? "अक्षांश" : "Latitude"}</td><td>${txt(d.latitude)}</td></tr>
    <tr><td class="label">${isHi ? "देशांतर" : "Longitude"}</td><td>${txt(d.longitude)}</td></tr>
    <tr><td class="label">${isHi ? "समय क्षेत्र" : "Timezone"}</td><td>${txt(d.timezone)}</td></tr>
    <tr><td class="label">${isHi ? "लग्न" : "Ascendant"}</td><td>${txt(chart.lagna)}</td></tr>
    <tr><td class="label">${isHi ? "चंद्र राशि" : "Moon Sign"}</td><td>${txt(chart.moonSign)}</td></tr>
    <tr><td class="label">${isHi ? "सूर्य राशि" : "Sun Sign"}</td><td>${txt(chart.sunSign)}</td></tr>
    <tr><td class="label">${isHi ? "नक्षत्र" : "Nakshatra"}</td><td>${txt(chart.nakshatra)}</td></tr>
  </table>
</div>
`;

  // Planet Positions
  html += `<div class="page-break">
  <h2>${isHi ? "ग्रह स्थिति" : "Planet Positions"}</h2>
  <table>
    <tr><th>${isHi ? "ग्रह" : "Planet"}</th><th>${isHi ? "राशि" : "Sign"}</th><th>${isHi ? "डिग्री" : "Degree"}</th><th>${isHi ? "भाव" : "House"}</th><th>${isHi ? "नक्षत्र" : "Nakshatra"}</th></tr>
`;
  for (const p of chart.planets) {
    html += `<tr><td>${txt(p.name)}</td><td>${txt(p.sign)}</td><td>${txt(p.degree)}</td><td>${txt(p.house)}</td><td>${txt(p.nakshatra)}</td></tr>`;
  }
  html += `</table></div>
`;

  // Houses
  html += `<div class="page-break">
  <h2>${isHi ? "भाव (12 घर)" : "Houses (12 Cusps)"}</h2>
  <table>
    <tr><th>${isHi ? "भाव" : "House"}</th><th>${isHi ? "राशि" : "Sign"}</th></tr>
`;
  for (const h of chart.houses) {
    html += `<tr><td>${txt(h.house)}</td><td>${txt(h.sign)}</td></tr>`;
  }
  html += `</table></div>
`;

  // Pillars
  for (const pillar of d.pillars) {
    const title = isHi && pillar.titleHi ? pillar.titleHi : pillar.titleEn;
    const narrative = isHi && pillar.narrativeHi ? pillar.narrativeHi : pillar.narrativeEn;
    const badges = pillar.badges || {};

    html += `<div class="page-break">
  <h2>${txt(title)}</h2>`;

    if (badges.score) html += `<p>${isHi ? "स्कोर" : "Score"}: ${txt(badges.score)}</p>`;
    if (badges.timeframe) html += `<p>${isHi ? "समय" : "Timeframe"}: ${txt(badges.timeframe)}</p>`;
    if (badges.lord) html += `<p>${isHi ? "अधिपति" : "Lord"}: ${txt(badges.lord)}</p>`;

    html += `<p>${txt(narrative)}</p>`;

    if (pillar.milestones && pillar.milestones.length > 0) {
      html += `<table>
    <tr><th>${isHi ? "अवधि" : "Period"}</th><th>${isHi ? "घटना" : "Event"}</th><th>${isHi ? "टिप्पणी" : "Note"}</th><th>${isHi ? "परिणाम" : "Outcome"}</th></tr>
`;
      for (const m of pillar.milestones) {
        const outcomeText = m.outcome === "positive" ? (isHi ? "शुभ" : "Positive") : m.outcome === "caution" ? (isHi ? "सावधान" : "Caution") : (isHi ? "तटस्थ" : "Neutral");
        html += `<tr><td>${txt(m.period)}</td><td>${txt(m.event)}</td><td>${txt(m.note)}</td><td>${outcomeText}</td></tr>`;
      }
      html += `</table>`;
    }
    html += `</div>
`;
  }

  // Doshas
  if (calc.doshas && calc.doshas.length > 0) {
    html += `<div class="page-break">
  <h2>${isHi ? "दोष विश्लेषण" : "Dosha Analysis"}</h2>`;
    for (const dosha of calc.doshas) {
      const statusText = dosha.isPresent ? (isHi ? "उपस्थित" : "Present") : (isHi ? "अनुपस्थित" : "Absent");
      html += `<table>
    <tr><td><b>${txt(dosha.name)}</b></td><td>${statusText} ${dosha.severity ? `(${txt(dosha.severity)})` : ""}</td></tr>
    <tr><td colspan="2">${txt(dosha.description)}</td></tr>
`;
      if (dosha.remedies && dosha.remedies.length > 0) {
        html += `<tr><td>${isHi ? "उपाय" : "Remedies"}</td><td>${dosha.remedies.map(r => txt(r)).join("; ")}</td></tr>`;
      }
      html += `</table>`;
    }
    html += `</div>
`;
  }

  // Yogas
  if (calc.yogas && calc.yogas.length > 0) {
    html += `<div class="page-break">
  <h2>${isHi ? "योग विश्लेषण" : "Yoga Analysis"}</h2>`;
    for (const yoga of calc.yogas) {
      const statusText = yoga.isPresent ? (isHi ? "उपस्थित" : "Present") : (isHi ? "अनुपस्थित" : "Absent");
      html += `<table>
    <tr><td><b>${txt(yoga.name)}</b></td><td>${statusText} ${yoga.strength ? `(${txt(yoga.strength)})` : ""}</td></tr>
    <tr><td colspan="2">${txt(yoga.description)}</td></tr>
`;
      if (yoga.impact) {
        html += `<tr><td>${isHi ? "प्रभाव" : "Impact"}</td><td>${txt(yoga.impact)}</td></tr>`;
      }
      if (yoga.planets && yoga.planets.length > 0) {
        html += `<tr><td>${isHi ? "ग्रह" : "Planets"}</td><td>${yoga.planets.map(p => txt(p)).join(", ")}</td></tr>`;
      }
      html += `</table>`;
    }
    html += `</div>
`;
  }

  // Dashas
  if (calc.vimshottari && calc.vimshottari.mahadashas && calc.vimshottari.mahadashas.length > 0) {
    const cd = calc.vimshottari.currentDasha;
    html += `<div class="page-break">
  <h2>${isHi ? "विम्शोत्तरी दशा" : "Vimshottari Dasha"}</h2>`;

    if (cd && cd.mahadasha) {
      html += `<table>
    <tr><td>${isHi ? "महादशा" : "Mahadasha"}</td><td>${txt(cd.mahadasha)}</td></tr>
    <tr><td>${isHi ? "अंतर्दशा" : "Antardasha"}</td><td>${txt(cd.antardasha)}</td></tr>
    <tr><td>${isHi ? "अवधि" : "Period"}</td><td>${txt(cd.startDate)} — ${txt(cd.endDate)}</td></tr>
  </table>`;
    }

    html += `<table>
    <tr><th>${isHi ? "अधिपति" : "Lord"}</th><th>${isHi ? "आरंभ" : "Start"}</th><th>${isHi ? "अंत" : "End"}</th><th>${isHi ? "वर्ष" : "Years"}</th></tr>
`;
    for (const md of calc.vimshottari.mahadashas) {
      html += `<tr><td>${txt(md.lord)}</td><td>${txt(md.startDate)}</td><td>${txt(md.endDate)}</td><td>${txt(md.years)}</td></tr>`;
    }
    html += `</table>`;

    for (const md of calc.vimshottari.mahadashas) {
      if (md.antardashas && md.antardashas.length > 0) {
        html += `<p><b>${txt(md.lord)} ${isHi ? "अंतर्दशाएं" : "Antardashas"}</b></p>
  <table>
    <tr><th>${isHi ? "ग्रह" : "Planet"}</th><th>${isHi ? "आरंभ" : "Start"}</th><th>${isHi ? "अंत" : "End"}</th></tr>
`;
        for (const ad of md.antardashas) {
          html += `<tr><td>${txt(ad.planet)}</td><td>${txt(ad.startDate)}</td><td>${txt(ad.endDate)}</td></tr>`;
        }
        html += `</table>`;
      }
    }
    html += `</div>
`;
  }

  // Closing
  html += `<div>
  <h2>${isHi ? "सारांश" : "Summary"}</h2>
  <table>
    <tr><td>${isHi ? "लग्न" : "Ascendant"}</td><td>${txt(chart.lagna)}</td></tr>
    <tr><td>${isHi ? "चंद्र राशि" : "Moon Sign"}</td><td>${txt(chart.moonSign)}</td></tr>
    <tr><td>${isHi ? "सूर्य राशि" : "Sun Sign"}</td><td>${txt(chart.sunSign)}</td></tr>
    <tr><td>${isHi ? "नक्षत्र" : "Nakshatra"}</td><td>${txt(chart.nakshatra)}</td></tr>
  </table>
  <p>${isHi ? "यह रिपोर्ट केवल मार्गदर्शन के लिए है।" : "This report is for guidance only."}</p>
</div>
`;

  html += `</body></html>`;
  return html;
}
